name: CI

on: [push, pull_request]

jobs:
    job:
        name: "${{ matrix.os_label }}"
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                name: [ ubuntu, macos ]
                include:
                    - name: ubuntu
                      os: ubuntu-latest
                      os_label: Ubuntu

                    - name: macos
                      os: macos-latest
                      os_label: MacOS

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    java-version: '11'
                    distribution: 'zulu'

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2

            -   name: Build with Gradle
                run: ./gradlew build

            -   name: Run tests
                run: ./gradlew test

            -   name: Upload Jacoco coverage report
                uses: actions/upload-artifact@v2
                with:
                    name: Jacoco report
                    path: build/jacocoHtml
